# Generated by Django 2.2.2 on 2019-06-12 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='person',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='person',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='app.Person'),
        ),
    ]
